import React from "react";
import { APP_CONFIG } from "@/lib/config";

export const metadata = {
  title: "Privacy Policy — W4Y MyDesk",
  description: "Privacy policy for W4Y MyDesk commercial system.",
};

export default function PrivacyPage() {
  return (
    <div className="py-16 md:py-24">
      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 space-y-8">
        <div>
          <span className="text-xs font-bold uppercase tracking-wider text-w4y-blue">Legal</span>
          <h1 className="mt-1 text-3xl font-extrabold text-w4y-dark dark:text-white">Privacy Policy</h1>
          <p className="text-xs text-w4y-secondary dark:text-w4y-dark-muted mt-2">Effective Date: 2026</p>
        </div>

        <div className="space-y-6 text-sm text-w4y-secondary dark:text-w4y-dark-muted leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-lg font-bold text-w4y-dark dark:text-white">1. Introduction</h2>
            <p>
              {APP_CONFIG.business.legalName} (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;) operates the website {APP_CONFIG.brand.domain} for the sale and licensing of the commercial product MyDesk. We respect your privacy and are committed to protecting the information you share with us.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-w4y-dark dark:text-white">2. Information We Collect</h2>
            <p>
              When you purchase a license or contact our support team, we collect only necessary commercial details:
            </p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>Full name</li>
              <li>Email address</li>
              <li>Phone number (optional)</li>
              <li>Business or legal firm name (optional)</li>
              <li>Transaction references generated by payment gateways</li>
            </ul>
            <p>
              We do not store your credit card numbers, CVVs, or bank account credentials on our servers.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-w4y-dark dark:text-white">3. Local Application Data</h2>
            <p>
              MyDesk is a downloadable desktop application. Your client dossiers, quotations, invoices, meeting minutes, and financial records reside on your local computer. We do not inspect or upload your proprietary business content to our servers.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-w4y-dark dark:text-white">4. Contact Information</h2>
            <p>
              For any privacy questions or requests to inspect your customer record, contact us directly at {APP_CONFIG.business.email}.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
